add_requires("bullet3")
add_rules("mode.debug")
add_rules("mode.release")

target("test")
set_kind("shared")
add_packages("bullet3")
add_files("test.c")
add_includedirs("include")
add_headerfiles("include/**.h")
