#ifndef _RETURN_CODES
#define _RETURN_CODES

#define MMD_NO_ERROR 0
#define MMD_NULL_PTR 1
#define MMD_FILE_NOT_FOUND 2
#define MMD_FILE_BUFFER_OVERFLOW 3
#define MMD_PMX_FILE_INVALID_HEADER 4
#define MMD_PMX_FILE_INVALID_INFO 5
#define MMD_PMX_FILE_INVALID_VERTICES 6
#define MMD_PMX_FILE_VERTEX_INVALID_BONETYPE 7
#define MMD_PMX_FILE_INVALID_FACES 8
#define MMD_PMX_FILE_INVALID_TEXTURES 9
#define MMD_PMX_FILE_INVALID_MATERIALS 10
#define MMD_PMX_FILE_INVALID_BONES 11
#define MMD_PMX_FILE_INVALID_MORPHS 12

#endif
